version: '2.1'
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn coverage
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test
      - node/test:
          test-results-path: coverage/clover.xml
