version: 2.1

orbs:
  node: circleci/node@16.10

jobs:
  test:
    docker:
      - image: cimg/node:16.10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
workflows:
  automated-tests-workflow:
    jobs:
      - test
